#! /bin/bash
#PBS -N "_CONF_._SRC_.mesons.cA211.30.32"
#PBS -q qcd
#PBS -l nodes=8:ppn=16
#PBS -l walltime=48:00:00
#PBS -o /scratch/tuf47161/cA211.30.32/log/_CONF_
#PBS -e /scratch/tuf47161/cA211.30.32/log/_CONF_

conf=_CONF_
s=_SRC_

module load hdf5/1.10.1-parallel

ENSEMBLE=cA211.30.32
MACHINE=OwlsNest

SCRATCH=/home/tuf47161/scratch

RUN_DIR=${SCRATCH}/${ENSEMBLE}
CORR_DIR=${RUN_DIR}/Corr        
PROP_DIR=${RUN_DIR}/Props
BIN_DIR=${HOME}/hadstruct-progs/src
BIN=mesons

INI_DIR=${HOME}/hadstruct-progs/${MACHINE}/${ENSEMBLE}/ini
RUN_INI_DIR=${RUN_DIR}/ini
INI_FILE=${conf}.${s}.ini.xml

cd ${RUN_DIR}

export LD_LIBRARY_PATH=${HOME}/install/lib:${LD_LIBRARY_PATH}
export OMP_NUM_THREADS=1

mkdir -p ${CORR_DIR}/${conf}
mkdir -p ${PROP_DIR}/${conf}
mkdir -p ${RUN_INI_DIR}/

cp ${BIN_DIR}/${BIN} ${RUN_DIR}/${BIN}
cp ${INI_DIR}/${INI_FILE} ${RUN_INI_DIR}/${INI_FILE}

RUN_CMD="mpirun ${RUN_DIR}/${BIN} ${INI_DIR}/${INI_FILE}"

date

echo "Run command is:"
echo "${RUN_CMD}"

eval ${RUN_CMD}

date


