#! /bin/bash
#PBS -N "_CONF_._SRC_.mesons.CPU.cA211.30.32"
#PBS -q qcd
#PBS -l nodes=8:ppn=16
#PBS -l walltime=48:00:00
#PBS -o /scratch/tuf47161/cA211.30.32/log/_CONF_
#PBS -e /scratch/tuf47161/cA211.30.32/log/_CONF_

conf="_CONF_"
s=_SRC_

ENSEMBLE=cA211.30.32
SCRATCH=/home/tuf47161/scratch

RUN_DIR=${SCRATCH}/${ENSEMBLE}
CORR_DIR=${RUN_DIR}/Corr        
PROP_DIR=${RUN_DIR}/Props
BIN_DIR=${HOME}/hadstruct-progs/src
BIN=mesons

INI_DIR=${HOME}/hadstruct-progs/OwlsNest/${ENSEMBLE}/ini
RUN_INI_DIR=${RUN_DIR}/ini
INI_FILE=${conf}.${s}.ini.xml

cd ${RUN_DIR}

module load mpi/openmpi/2.1.1
module load hdf5/1.10.1-parallel
module load intel-libs/2017.4.196

export LD_LIBRARY_PATH=${HOME}/install/lib:${LD_LIBRARY_PATH}
export OMP_NUM_THREADS=1

mkdir -p ${CORR_DIR}/${conf}
mkdir -p ${PROP_DIR}/${conf}
mkdir -p ${RUN_INI_DIR}/

#cp ${BIN_DIR}/${BIN} ${RUN_DIR}/${BIN}
#cp ${INI_DIR}/${INI_FILE} ${RUN_INI_DIR}/${INI_FILE}

LOG_DIR=${RUN_DIR}/log/${CONF}
mkdir -p ${LOG_DIR}
OUTPUT=${LOG_DIR}/${PBS_JOBNAME}.${PBS_JOBID}.out

RUN_CMD="mpirun ${BIN_DIR}/${BIN} ${INI_DIR}/${INI_FILE}"

date > ${OUTPUT}

echo "Run command is:" >> ${OUTPUT}
echo "${RUN_CMD}" >> ${OUTPUT}

eval ${RUN_CMD} >> ${OUTPUT}

date >> ${OUTPUT}


